name: Testing various queries

on:
  push
    
jobs:
  static-query:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: samples/repository-static.query.yaml
        logLevel: debug
  args-query:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: samples/repository-args.query.yaml
        logLevel: debug
        owner: helaili
        name: github-graphql-action
  jq-query:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: samples/repository-jq.query.yaml
        logLevel: debug
  introspection-query:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: samples/introspection.query.yaml
        logLevel: debug
        accept: application/vnd.github.elektra-preview+json